#!/bin/bash
exec 1> >(logger -s -p daemon.info -t ${PWD##*/})
exec 2> >(logger -s -p daemon.error -t ${PWD##*/})

echo "Starting nginx process..."
exec /usr/sbin/nginx -g 'daemon off; master_process on;'
